### ISSUE TITLE
I have a problem with pool sevabit

### ISSUE THREAD

**Issue by hardx4** [sevabit/sevabit#4]
I have been trying to create a sevabit pool with cryptonote-nodejs but I have not been successful. The currency daemon is synchronized and the wallet in RPC mode, when I try to connect the miner, the error occurs.

![image](https://user-images.githubusercontent.com/7688208/63538124-3bb84e00-c4e5-11e9-8d67-a44f1312d4fd.png)

My conf is:
"daemonType": "default",
"cnAlgorithm": "cryptonight_heavy",
"cnVariant": null,
"cnBlobType": 0,

Could you tell me if this is correct? What if there are any major changes that have to be made to pool.js?

**Comment by scilicet64** [comment]
this is no issue, please ask the community for help. this is an issue tracker.

You are using CN heavy while we have another algorithm.
